name: tomato-ripeness
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3
  - torchvision
  - torchaudio
  - cudatoolkit=12.1
  - pip:
      - ultralytics>=8.3.0
      - timm>=0.9.16
      - ensemble-boxes>=1.0.9
      - pycocotools>=2.0.7
      - albumentations>=1.3.1
      - opencv-python>=4.8.0
      - pandas
      - matplotlib
      - seaborn
      - tqdm
      - tensorboard
      - wandb
      - scipy
      - numpy
      - Pillow
      - ruamel.yaml
      - rfdetr @ git+https://github.com/roboflow/rf-detr.git
