framework: ultralytics
model: "yolo12s.pt"
task: detect
imgsz: 1280
batch: auto
epochs: 300
optimizer: AdamW
lr0: 0.002
lrf: 0.15
warmup_epochs: 5
weight_decay: 0.0005
momentum: 0.937
label_smoothing: 0.05
patience: 30
seed: 42
deterministic: true
augmentations: configs/augmentations.yaml::lite
val_interval: 10
save_json: true
project: runs/yolov12_s
name: tomato
notes: |
  Baseline YOLOv12-s run with lite augmentations and 1280 square inputs.
  Enable auto-anchor and classify 3 tomato ripeness classes.
